spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    
tdt:
  dbcp:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tdt?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456   
   
etlapi:
  dbcp:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmss?&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    
mongo:
  db:
    name: hxjf
    host: 127.0.0.1   
