dbcp:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tdt?characterEncoding=utf8&useSSL=false
  username: root
  password: 123456
  
spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
